#!/bin/bash

symlink() {
  src=`pwd`/$1
  dest="$HOME/.$1"
  ln -fs $src $dest
}

symlink gitconfig
symlink tmux.conf
symlink zshrc
symlink vim
symlink gvimrc
symlink vimrc

if [ ! -d ~/.vim/bundle/vundle/.git ]; then
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
  vim +BundleInstall +qall
fi
